config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :posts do
    get :feeds, on: :collection
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  controller :sessions do
    get 'login' => :new, as: :login
    post 'login' => :create
    delete 'logout' => :destroy, as: :logout
  end

  resources :relationships, only: %i[create destroy]

  root 'sessions#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  DESCRIPTION_MIN_LENGTH = 10

  belongs_to :user

  validates :user_id, :description, presence: true
  validates :description, length: { minimum: DESCRIPTION_MIN_LENGTH },
                       		if: -> { description }

  default_scope -> { order(created_at: :desc) }
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = current_user.posts.paginate(page: params[:page], per_page: 5)
  end

  def show; end

  def new
    @post = Post.new
  end

  def edit; end

  def create
    @post = current_user.posts.new(post_params)

    # storing the Cloudinary link in the post image field
    unless params[:post][:photo].blank?
      @post[:photo] = upload_post_image(params)['secure_url']
    end

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      flash.now[:error] = I18n.t(:form_has_errors, scope: 'errors.messages')
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @post.update(post_params)

      # updating the Cloudinary link in the post image field
      unless params[:post][:photo].blank?
        @post.update(photo: upload_post_image(params)['secure_url'])
      end
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      flash.now[:error] = I18n.t(:form_has_errors, scope: 'errors.messages')
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy

    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  def feeds
    @posts = current_user.feed.paginate(page: params[:page], per_page: 5)
  end

  private

  def upload_post_image(params)
    Cloudinary::Uploader.upload(params[:post][:photo],
                                folder: 'fake_twitter',
                                transformation: { width: 500, height: 500,
                                                  crop: 'fill' })
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:user_id, :description, :photo)
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    
    <%= form.text_area :description %>

    <% if @post.errors[:description] %>
      <% @post.errors[:description].each do |message| %>
        <p class="errorMessage">
          <%= message %>
        </p>
      <% end %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    
    <%= form.file_field :photo %>

    <% if @post.errors[:photo] %>
      <% @post.errors[:photo].each do |message| %>
        <p class="errorMessage">
          <%= message %>
        </p>
      <% end %>
    <% end %>
  </div>

  <div class="actions">
    <% if @post.persisted? %>
      <button type="submit" name="commit" class="addButton">
        <i class="fa fa-floppy-o" aria-hidden="true"></i>Update Post
      </button>

      <%= link_to '<i class="fa fa-times-circle" aria-hidden="true"></i>Cancel'.html_safe, @post, class: "destroyButton" %>
    <% else %>
      <button type="submit" name="commit" class="addButton">
        <i class="fa fa-floppy-o" aria-hidden="true"></i>Create Post
      </button>
      <%= link_to '<i class="fa fa-times-circle" aria-hidden="true"></i>Cancel'.html_safe, users_path, class: "destroyButton" %>
    <% end %>
  </div>
<% end %>

app/views/posts/_posts_layout.html.erb
<table class="scaffoldListTable">
  <thead>
    <tr>
      <th>Post Id</th>
      
      <th>Created By</th>
      
      <th>Description</th>
      
      <th>Photo</th>
      
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% posts.each do |post| %>
      <tr>
        <td><%= link_to post.id, post %></td>
        
        <td><%= post.user.username %></td>
        
        <td><%= post.description %></td>
        
        <td><img src="<%= post.photo %>" alt="can't display image" style="width: 150px;"></td>
        
        <% if @current_user.id == post.user.id %>
          <td><%= link_to '<i class="fa fa-eye" aria-hidden="true"></i>'.html_safe, post %></td>
          
          <td>
            <%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i>'.html_safe, edit_post_path(post), title: "Edit User" %>
          </td>
          
          <td>
            <%= link_to '<i class="fa fa-trash" aria-hidden="true"></i>'.html_safe, post, method: :delete, data: { confirm: "Are you sure you want to delete this post?" }, title: "Delete Post" %>
          </td>
        <% else %>
          <td></td>
          
          <td></td>
          
          <td></td>
        <% end %>
      </tr>
    <% end %>
  
  </tbody>
</table>
<%= will_paginate posts, class: "apple_pagination" %>

app/views/posts/edit.html.erb
<section class='scaffold'>
  <h2 class="breadcrumbs">
    <%= link_to "Posts", posts_path %>
    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
    <%= link_to @post.id, post_path(@post.id) %>
    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
    Editing
  </h2>

  <%= render "form", user: @post %>
</section>

app/views/posts/feeds.html.erb
<section class='scaffold'>
  <h2 class="breadcrumbs">Our's Feeds</h2>
  
  <%= render 'posts_layout', posts: @posts %>
</section>

app/views/posts/index.html.erb
<section class='scaffold'>
  <h2 class="breadcrumbs">Posts</h2>

  <div style="margin-bottom: 15px; text-align: right;"><%= link_to '<i class="fa fa-user-plus" aria-hidden="true"></i>New Post'.html_safe, new_post_path, class: 'addButton' %></div>

  <%= render 'posts_layout', posts: @posts %>
</section>

app/views/posts/new.html.erb
<section class='scaffold'>
	<h2 class="breadcrumbs">
		New Post
	</h2>

	<%= render "form", user: @post %>
</section>

app/views/posts/show.html.erb
<section class='scaffold'>
  <h2 class="breadcrumbs">
    <%= link_to "Post", posts_path %>
    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
    <%= @post.id %>
  </h2>
  
  <div class="posts-layout">
    <div class="post-card">
      <img class="image" src="<%= @post.photo if @post.photo.present? %>">
      
      <div class="title">
        <em>Created By:</em>
        <strong><%= @post.user.username %></strong>
        <i><%= time_ago_in_words(@post.created_at)%> ago</i>
      </div>
      
      <div class="body-trunc">
        <p><%= @post.description %></p>
      </div>
      
      <div class="post-footer">
        <p style="text-align: center;">
          <% if @current_user.id == @post.user.id %>
            <%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i>'.html_safe, edit_post_path(@post), class: "defaultButton" %>
            <%= link_to '<i class="fa fa-trash" aria-hidden="true"></i>'.html_safe, @post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'destroyButton' %>
          <% end %>
        </p>
      </div>
    </div>
  </div>

</section>