config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :posts do
    get :feeds, on: :collection
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  controller :sessions do
    get 'login' => :new, as: :login
    post 'login' => :create
    delete 'logout' => :destroy, as: :logout
  end

  resources :relationships, only: %i[create destroy]

  root 'sessions#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/sidebar/_current_user_info.html.erb
<section id="sidebar-nav-user">
  <div class="username">
    <center>
      <%= render "users/avatar", user: @current_user, small: false%>
      <%= link_to @current_user.username, @current_user %>      
    </center>
  </div>
</section>

app/views/layouts/sidebar/_navigation.html.erb
<ul class="nav">
  <li style="width: 80%; display: inline-block;">
    <%= link_to '<i class="fa fa-group" aria-hidden="true"></i>Following'.html_safe, following_user_path(@current_user) %>
  </li>
  <p class="following_count"><%= @current_user.following.count %></p>

  <li style="width: 80%; display: inline-block;">
    <%= link_to '<i class="fa fa-users" aria-hidden="true"></i>Followers'.html_safe, followers_user_path(@current_user) %>
  </li>
  <p class="followers_count"><%= @current_user.followers.count %></p>
  
  <li>
    <%= link_to '<i class="fa fa-cog fa-spin" aria-hidden="true"></i>All Users'.html_safe, users_path %>
  </li>

  <li>
    <div class="dropdown">
      <i class="fa fa-tasks" aria-hidden="true" style="margin-left: 16px; color: #153d77"></i>
      <button class="dropbtn">Posts</button>
      <div class="dropdown-content">
        <%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i>Create'.html_safe, new_post_path %>
        <%= link_to '<i class="fa fa-rss" aria-hidden="true"></i>My Feeds'.html_safe, posts_path %>
        <%= link_to '<i class="fa fa-rss-square" aria-hidden="true"></i>Feeds'.html_safe, feeds_posts_path %>
      </div>
    </div>
  </li>

  <li class='border'></li>

  <li>
    <%= link_to '<i class="fa fa-sign-out" aria-hidden="true"></i>Logout'.html_safe, logout_path, method: :delete, class: "defaultButton" %>
  </li>
</ul>

app/views/layouts/sidebar/_sidebar.html.erb
<section id="sidebar">
  <section id="sidebar-header">
    <a href="<%= root_path %>">      
      <span>Lookalike</span>
      <i class="fa fa-twitter" aria-hidden="true"></i>
    </a>
  </section>

  <% if current_user %>
    <section id="sidebar-nav">
      <%= render "layouts/sidebar/current_user_info" %>

      <%= render "layouts/sidebar/navigation" %>
    </section>
  <% else %>
    <center>
      <div style="margin-top: 50%;">
        <%= link_to '<i class="fa fa-user-plus" aria-hidden="true"></i>Sign Up'.html_safe, new_user_path, class: "addButton", :style => 'display: block;' %>
      </div>

      <div style="margin-top: 25px;">
        <%= link_to '<i class="fa fa-sign-in" aria-hidden="true"></i>Log In'.html_safe, root_path, class: "defaultButton", :style => 'display: block;' %>
      </div>
    </center>
  <% end %>
</section>